---
# The provision script can take a yaml file with provision options
# This is a dictionary of command-line arguments for the provisioning script
force: False
samples: False
sample-collection: Sample Images
sample-folder: Images
# Set use_defaults to False to skip default settings
use_defaults: True
# Set mongo_compat to False to not automatically set the mongo feature
# compatibility version to the current server version.
mongo_compat: True
# A list of additional pip modules to install; if any are girder plugins with
# client-side code, also specify rebuild-client.
# pip:
#   - girder-oauth
#   - girder-ldap
# rebuild-client may be False, True (for dev mode), or "production"
rebuild-client: False
# Default admin user if there are no admin users
admin:
  login: admin
  password: password
  firstName: Admin
  lastName: Admin
  email: admin@nowhere.nil
  public: True
# Default assetstore if there are no assetstores
assetstore:
  method: createFilesystemAssetstore
  name: Assetstore
  root: /assetstore
# Any resources to ensure exist.  A model must be specified.  This creates the
# resource if there is no match for all specified values.  A value of
# "resource:<path>" is converted to the resource document with that resource
# path.  "resource:admin" uses the default admin, "resourceid:<path>" is the
# string id for the resource path, and "resourceid:admin" is the string if for
# default admin.
resources:
  - model: collection
    name: Tasks
    creator: resource:admin
    public: True
  - model: folder
    resourcepath: "collection/Tasks/Slicer CLI Web Tasks"
    parent: resource:collection/Tasks
    parentType: collection
    name: "Slicer CLI Web Tasks"
    creator: resource:admin
    public: True
settings:
  worker.broker: "amqp://guest:guest@rabbitmq"
  worker.backend: "rpc://guest:guest@rabbitmq"
  worker.api_url: "http://girder:8080/api/v1"
  worker.direct_path: True
  core.brand_name: "Digital Slide Archive"
  histomicsui.webroot_path: "histomics"
  histomicsui.alternate_webroot_path: "histomicstk"
  histomicsui.delete_annotations_after_ingest: True
  homepage.markdown: |
    # Digital Slide Archive
    ---
    ## Bioinformatics Platform

    Welcome to the **Digital Slide Archive**.

    Developers who want to use the Girder REST API should check out the
    [interactive web API docs](api/v1).

    The [HistomicsUI](histomics) application is enabled.
  slicer_cli_web.task_folder: "resourceid:collection/Tasks/Slicer CLI Web Tasks"
# List slicer-cli-images to pull and load
# slicer-cli-image:
#   - dsarchive/histomicstk:latest
